version: '3.8'
services:
  db:
    image: postgres:15
    container_name: gym-postgres
    environment:
      POSTGRES_DB: gym
      POSTGRES_USER: gymuser
      POSTGRES_PASSWORD: gympass
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: gym-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gym
      SPRING_DATASOURCE_USERNAME: gymuser
      SPRING_DATASOURCE_PASSWORD: gympass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db